export const roles = [
  {
    id: 1,
    name: "ADMIN",
  },
  {
    id: 2,
    name: "SUPERADMIN",
  },
];

export const apps = [
  {
    id: 1,
    name: "Admin",
    origin: "admin-origin",
    supportedRoles: roles,
  },
  {
    id: 2,
    name: "User",
    origin: "admin-origin",
    supportedRoles: [
      {
        id: 2,
        name: "USER",
      },
    ],
  },
];

export const allUsers = [
  {
    disabled: false,
    email: "john@prefabs.tech.com",
    givenName: "John",
    id: "user-1",
    invitedBy: null,
    isActiveUser: true,
    name: "John Doe",
    roles: ["USER"],
    signedUpAt: "2023-08-10T08:00:00Z",
    surname: "Doe",
    username: "johndoe",
  },
  {
    disabled: true,
    email: "jane@prefabs.tech.com",
    givenName: "Jane",
    id: "invitation-123",
    invitedBy: {
      email: "admin@prefabs.tech.com",
      givenName: "Admin",
      id: "user-2",
      isActiveUser: true,
      roles: ["USER"],
      surname: "User",
      username: "admin",
    },
    isActiveUser: false,
    name: "Jane Smith",
    roles: ["ADMIN"],
    surname: "Smith",
    username: "janesmith",
  },
  {
    disabled: false,
    email: "alice@prefabs.tech.com",
    givenName: "Alice",
    id: "user-3",
    invitedBy: null,
    isActiveUser: true,
    name: "Alice Johnson",
    roles: ["USER"],
    signedUpAt: "2023-08-08T10:30:00Z",
    surname: "Johnson",
    username: "alicej",
  },
  {
    disabled: false,
    email: "bob@prefabs.tech.com",
    givenName: "Bob",
    id: "invitation-456",
    invitedBy: {
      email: "charlie@prefabs.tech.com",
      givenName: "Charlie",
      id: "user-4",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Brown",
      username: "charlieb",
    },
    isActiveUser: false,
    name: "Bob Williams",
    roles: ["ADMIN"],
    surname: "Williams",
    username: "bobw",
  },
  {
    disabled: true,
    email: "george@prefabs.tech.com",
    givenName: "george",
    id: "user-6",
    invitedBy: null,
    isActiveUser: true,
    name: "George Williams",
    roles: ["USER"],
    signedUpAt: "2023-10-10T08:00:00Z",
    surname: "williams",
    username: "george",
  },
];

export const invitations = [
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-05").getTime(),
    email: "bob@prefabs.tech.com",
    expiresAt: new Date("2024-02-04").getTime(),
    id: 456,
    invitedBy: {
      disabled: false,
      email: "charlie@prefabs.tech.com",
      givenName: "Charlie",
      id: "user-4",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Brown",
      username: "charlieb",
    },
    invitedById: "user-4",
    payload: null,
    revokedAt: new Date("2024-01-14").getTime(),
    role: "USER",
    updatedAt: new Date("2024-01-14").getTime(),
  },
  {
    acceptedAt: null,
    appId: 3,
    createdAt: new Date("2024-01-05").getTime(),
    email: "jane@prefabs.tech.com",
    expiresAt: new Date("2024-02-04").getTime(),
    givenName: "Jane",
    id: 123,
    invitedBy: {
      disabled: false,
      email: "admin@prefabs.tech.com",
      givenName: "Admin",
      id: "user-2",
      isActiveUser: true,
      roles: ["USER"],
      surname: "User",
      username: "admin",
    },
    invitedById: "user-2",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-01-24").getTime(),
  },
  {
    acceptedAt: new Date("2024-02-24").getTime(),
    appId: 2,
    createdAt: new Date("2024-01-05").getTime(),
    email: "june@prefabs.tech.com",
    expiresAt: new Date().getTime() + 4 * 24 * 60 * 60 * 1000,
    id: 789,
    invitedBy: {
      disabled: true,
      email: "jonny@prefabs.tech.com",
      givenName: "jonny",
      id: "user-8",
      isActiveUser: true,
      roles: ["USER"],
      surname: "smith",
      username: "admin",
    },
    invitedById: "user-8",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-01-24").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-05").getTime(),
    email: "janet@prefabs.tech.com",
    expiresAt: new Date().getTime() + 4 * 24 * 60 * 60 * 1000,
    id: 789,
    invitedBy: {
      disabled: true,
      email: "jolly@prefabs.tech.com",
      givenName: "jolly",
      id: "user-8",
      isActiveUser: true,
      roles: ["USER"],
      surname: "doe",
      username: "admin",
    },
    invitedById: "user-8",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-01-24").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-10").getTime(),
    email: "alexander.smith1234@prefabs.tech.com",
    expiresAt: new Date().getTime() + 4 * 24 * 60 * 60 * 1000,
    id: 890,
    invitedBy: {
      disabled: true,
      email: "michelle.williams@prefabs.tech.com",
      givenName: "Michelle Alexandra",
      id: "user-15",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Williams-Smithson",
      username: "admin",
    },
    invitedById: "user-15",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-01-24").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-03-01").getTime(),
    email: "george.harrison@prefabs.tech.com",
    expiresAt: new Date("2024-05-01").getTime(),
    id: 891,
    invitedBy: {
      disabled: false,
      email: "robert.johnson@prefabs.tech.com",
      givenName: "Robert James",
      id: "user-22",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Johnson-Longstreet",
      username: "moderator_robert",
    },
    invitedById: "user-22",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-03-03").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-15").getTime(),
    email: "lucas.martins@prefabs.techech.com",
    expiresAt: new Date("2024-03-15").getTime(),
    id: 892,
    invitedBy: {
      disabled: true,
      email: "david.jones@prefabs.tech.com",
      givenName: "David William",
      id: "user-34",
      isActiveUser: true,
      roles: ["ADMIN", "MODERATOR"],
      surname: "Jones-Smith",
      username: "admin_david_jones",
    },
    invitedById: "user-34",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-01-18").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-02-18").getTime(),
    email: "olivia.clark@prefabs.tech.com",
    expiresAt: new Date("2024-04-20").getTime(),
    id: 893,
    invitedBy: {
      disabled: false,
      email: "luke.martin@prefabs.tech.com",
      givenName: "Luke Robert",
      id: "user-18",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Martin",
      username: "user_luke",
    },
    invitedById: "user-18",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-02-21").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-03-05").getTime(),
    email: "jackson.davis@prefabs.tech.com",
    expiresAt: new Date("2024-05-05").getTime(),
    id: 894,
    invitedBy: {
      disabled: false,
      email: "emma.white@prefabs.tech.com",
      givenName: "Emma Nicole",
      id: "user-27",
      isActiveUser: true,
      roles: ["ADMIN", "MODERATOR"],
      surname: "White",
      username: "superadmin_emma",
    },
    invitedById: "user-27",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-03-07").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-02-05").getTime(),
    email: "sophia.brown@prefabs.tech.com",
    expiresAt: new Date("2024-04-06").getTime(),
    id: 895,
    invitedBy: {
      disabled: false,
      email: "michael.green@prefabs.tech.com",
      givenName: "Michael Christopher",
      id: "user-10",
      isActiveUser: true,
      roles: ["ADMIN", "USER"],
      surname: "Green",
      username: "admin_michael",
    },
    invitedById: "user-10",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-02-12").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-28").getTime(),
    email: "madeline.james@prefabs.tech.com",
    expiresAt: new Date("2024-03-28").getTime(),
    id: 896,
    invitedBy: {
      disabled: true,
      email: "brandon.kelly@prefabs.tech.org",
      givenName: "Brandon Nathaniel",
      id: "user-20",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Kelly",
      username: "admin_bkelly",
    },
    invitedById: "user-20",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-02-01").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-03-10").getTime(),
    email: "ethan.miller@prefabs.tech.com",
    expiresAt: new Date("2024-05-10").getTime(),
    id: 897,
    invitedBy: {
      disabled: false,
      email: "hannah.morris@prefabs.tech.com",
      givenName: "Hannah",
      id: "user-5",
      isActiveUser: true,
      roles: ["ADMIN"],
      surname: "Morris",
      username: "admin_hannah",
    },
    invitedById: "user-5",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-03-12").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-02-25").getTime(),
    email: "benjamin.martinez@prefabs.tech.com",
    expiresAt: new Date("2024-04-25").getTime(),
    id: 898,
    invitedBy: {
      disabled: false,
      email: "lucy.rodriguez@prefabs.tech.net",
      givenName: "Lucy Isabella",
      id: "user-12",
      isActiveUser: true,
      roles: ["ADMIN"],
      surname: "Rodriguez",
      username: "superadmin_lucy",
    },
    invitedById: "user-12",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-02-28").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-30").getTime(),
    email: "claire.morgan@prefabs.tech.com",
    expiresAt: new Date("2024-03-30").getTime(),
    id: 899,
    invitedBy: {
      disabled: false,
      email: "jacob.smith@prefabs.tech.com",
      givenName: "Jacob",
      id: "user-16",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Smith",
      username: "user_jacobsmith",
    },
    invitedById: "user-16",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-02-02").getTime(),
  },
];
